name: Input params

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Describe the input param'
        default: 'Pavan Kumar'
        required: true

jobs:
  packer-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send greetings
        run: echo "Hello {{ github.event.inputs.name }}"
